services:
  - type: web
    name: epargnplus-web
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_API_URL
        value: https://epargnplus-api.onrender.com/v1
    autoDeploy: true
